/*
 *   Copyright (C) 2014-2017 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.product.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class FareTemplateBase<M extends FareTemplateBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        NAME("name"),
        SHOP_ADDR("shop_addr"),
        DISPATCH_TIME("dispatch_time"),
        IS_INCL_POSTAGE("is_incl_postage"),
        VALUATION_MODEL("valuation_model"),
        IS_INCL_POSTAGE_BY_IF("is_incl_postage_by_if"),
        LAST_MODIFIED_DATE("last_modified_date"),
        TITLE("title"),
        CONTENT("content"),
        MESSAGE_FORMAT("message_format");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setName(String var) {
        set(Fields.NAME.toString(), var);
    }

    public String getName() {
        return (String) get(Fields.NAME.toString());
    }

    public void setShopAddr(String var) {
        set(Fields.SHOP_ADDR.toString(), var);
    }

    public String getShopAddr() {
        return (String) get(Fields.SHOP_ADDR.toString());
    }

    public void setDispatchTime(String var) {
        set(Fields.DISPATCH_TIME.toString(), var);
    }

    public String getDispatchTime() {
        return (String) get(Fields.DISPATCH_TIME.toString());
    }

    public void setIsInclPostage(Integer var) {
        set(Fields.IS_INCL_POSTAGE.toString(), var);
    }

    public Integer getIsInclPostage() {
        return (Integer) get(Fields.IS_INCL_POSTAGE.toString());
    }

    public void setValuationModel(Integer var) {
        set(Fields.VALUATION_MODEL.toString(), var);
    }

    public Integer getValuationModel() {
        return (Integer) get(Fields.VALUATION_MODEL.toString());
    }

    public void setIsInclPostageByIf(Integer var) {
        set(Fields.IS_INCL_POSTAGE_BY_IF.toString(), var);
    }

    public Integer getIsInclPostageByIf() {
        return (Integer) get(Fields.IS_INCL_POSTAGE_BY_IF.toString());
    }

    public void setLastModifiedDate(Date var) {
        set(Fields.LAST_MODIFIED_DATE.toString(), var);
    }

    public Date getLastModifiedDate() {
        return (Date) get(Fields.LAST_MODIFIED_DATE.toString());
    }

    public void setTitle(String var) {
        set(Fields.TITLE.toString(), var);
    }

    public String getTitle() {
        return (String) get(Fields.TITLE.toString());
    }

    public void setContent(String var) {
        set(Fields.CONTENT.toString(), var);
    }

    public String getContent() {
        return (String) get(Fields.CONTENT.toString());
    }

    public void setMessageFormat(String var) {
        set(Fields.MESSAGE_FORMAT.toString(), var);
    }

    public String getMessageFormat() {
        return (String) get(Fields.MESSAGE_FORMAT.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
