/*
 *   Copyright (C) 2014-2017 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.product.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class ProductSpecificationBase<M extends ProductSpecificationBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        PRODUCT_ID("product_id"),
        NAME("name"),
        STOCK_BALANCE("stock_balance"),
        PRICE("price"),
        COST_PRICE("cost_price"),
        SUGGESTED_PRICE("suggested_price"),
        WEIGHT("weight"),
        BULK("bulk");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setProductId(Integer var) {
        set(Fields.PRODUCT_ID.toString(), var);
    }

    public Integer getProductId() {
        return (Integer) get(Fields.PRODUCT_ID.toString());
    }

    public void setName(String var) {
        set(Fields.NAME.toString(), var);
    }

    public String getName() {
        return (String) get(Fields.NAME.toString());
    }

    public void setStockBalance(Integer var) {
        set(Fields.STOCK_BALANCE.toString(), var);
    }

    public Integer getStockBalance() {
        return (Integer) get(Fields.STOCK_BALANCE.toString());
    }

    public void setPrice(BigDecimal var) {
        set(Fields.PRICE.toString(), var);
    }

    public BigDecimal getPrice() {
        return (BigDecimal) get(Fields.PRICE.toString());
    }

    public void setCostPrice(BigDecimal var) {
        set(Fields.COST_PRICE.toString(), var);
    }

    public BigDecimal getCostPrice() {
        return (BigDecimal) get(Fields.COST_PRICE.toString());
    }

    public void setSuggestedPrice(BigDecimal var) {
        set(Fields.SUGGESTED_PRICE.toString(), var);
    }

    public BigDecimal getSuggestedPrice() {
        return (BigDecimal) get(Fields.SUGGESTED_PRICE.toString());
    }

    public void setWeight(Integer var) {
        set(Fields.WEIGHT.toString(), var);
    }

    public Integer getWeight() {
        return (Integer) get(Fields.WEIGHT.toString());
    }

    public void setBulk(Integer var) {
        set(Fields.BULK.toString(), var);
    }

    public Integer getBulk() {
        return (Integer) get(Fields.BULK.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
