/*
 *   Copyright (C) 2014-2017 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.product.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class ProductBase<M extends ProductBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        CATEGORY_ID("category_id"),
        BRAND_ID("brand_id"),
        NAME("name"),
        SHORT_NAME("short_name"),
        COVER("cover"),
        STOCK_BALANCE("stock_balance"),
        SALES("sales"),
        STATUS("status"),
        CREATED_DATE("created_date"),
        LAST_MODIFIED_DATE("last_modified_date"),
        UNIT("unit"),
        PRICE("price"),
        COST_PRICE("cost_price"),
        SUGGESTED_PRICE("suggested_price"),
        PROMOTED("promoted"),
        FREIGHT("freight"),
        FREE_SHIPPING("free_shipping"),
        SORT_ORDER("sort_order"),
        PARTNER_LEVEL_ZONE("partner_level_zone"),
        VIEW_COUNT("view_count"),
        FARE_ID("fare_id"),
        BARCODE("barcode"),
        STORE_LOCATION("store_location"),
        WEIGHT("weight"),
        BULK("bulk");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setCategoryId(Integer var) {
        set(Fields.CATEGORY_ID.toString(), var);
    }

    public Integer getCategoryId() {
        return (Integer) get(Fields.CATEGORY_ID.toString());
    }

    public void setBrandId(Integer var) {
        set(Fields.BRAND_ID.toString(), var);
    }

    public Integer getBrandId() {
        return (Integer) get(Fields.BRAND_ID.toString());
    }

    public void setName(String var) {
        set(Fields.NAME.toString(), var);
    }

    public String getName() {
        return (String) get(Fields.NAME.toString());
    }

    public void setShortName(String var) {
        set(Fields.SHORT_NAME.toString(), var);
    }

    public String getShortName() {
        return (String) get(Fields.SHORT_NAME.toString());
    }

    public void setCover(String var) {
        set(Fields.COVER.toString(), var);
    }

    public String getCover() {
        return (String) get(Fields.COVER.toString());
    }

    public void setStockBalance(Integer var) {
        set(Fields.STOCK_BALANCE.toString(), var);
    }

    public Integer getStockBalance() {
        return (Integer) get(Fields.STOCK_BALANCE.toString());
    }

    public void setSales(Integer var) {
        set(Fields.SALES.toString(), var);
    }

    public Integer getSales() {
        return (Integer) get(Fields.SALES.toString());
    }

    public void setStatus(String var) {
        set(Fields.STATUS.toString(), var);
    }

    public String getStatus() {
        return (String) get(Fields.STATUS.toString());
    }

    public void setCreatedDate(Date var) {
        set(Fields.CREATED_DATE.toString(), var);
    }

    public Date getCreatedDate() {
        return (Date) get(Fields.CREATED_DATE.toString());
    }

    public void setLastModifiedDate(Date var) {
        set(Fields.LAST_MODIFIED_DATE.toString(), var);
    }

    public Date getLastModifiedDate() {
        return (Date) get(Fields.LAST_MODIFIED_DATE.toString());
    }

    public void setUnit(String var) {
        set(Fields.UNIT.toString(), var);
    }

    public String getUnit() {
        return (String) get(Fields.UNIT.toString());
    }

    public void setPrice(BigDecimal var) {
        set(Fields.PRICE.toString(), var);
    }

    public BigDecimal getPrice() {
        return (BigDecimal) get(Fields.PRICE.toString());
    }

    public void setCostPrice(BigDecimal var) {
        set(Fields.COST_PRICE.toString(), var);
    }

    public BigDecimal getCostPrice() {
        return (BigDecimal) get(Fields.COST_PRICE.toString());
    }

    public void setSuggestedPrice(BigDecimal var) {
        set(Fields.SUGGESTED_PRICE.toString(), var);
    }

    public BigDecimal getSuggestedPrice() {
        return (BigDecimal) get(Fields.SUGGESTED_PRICE.toString());
    }

    public void setPromoted(Integer var) {
        set(Fields.PROMOTED.toString(), var);
    }

    public Integer getPromoted() {
        return (Integer) get(Fields.PROMOTED.toString());
    }

    public void setFreight(BigDecimal var) {
        set(Fields.FREIGHT.toString(), var);
    }

    public BigDecimal getFreight() {
        return (BigDecimal) get(Fields.FREIGHT.toString());
    }

    public void setFreeShipping(Integer var) {
        set(Fields.FREE_SHIPPING.toString(), var);
    }

    public Integer getFreeShipping() {
        return (Integer) get(Fields.FREE_SHIPPING.toString());
    }

    public void setSortOrder(Integer var) {
        set(Fields.SORT_ORDER.toString(), var);
    }

    public Integer getSortOrder() {
        return (Integer) get(Fields.SORT_ORDER.toString());
    }

    public void setPartnerLevelZone(Integer var) {
        set(Fields.PARTNER_LEVEL_ZONE.toString(), var);
    }

    public Integer getPartnerLevelZone() {
        return (Integer) get(Fields.PARTNER_LEVEL_ZONE.toString());
    }

    public void setViewCount(Long var) {
        set(Fields.VIEW_COUNT.toString(), var);
    }

    public Long getViewCount() {
        return (Long) get(Fields.VIEW_COUNT.toString());
    }

    public void setFareId(Integer var) {
        set(Fields.FARE_ID.toString(), var);
    }

    public Integer getFareId() {
        return (Integer) get(Fields.FARE_ID.toString());
    }

    public void setBarcode(String var) {
        set(Fields.BARCODE.toString(), var);
    }

    public String getBarcode() {
        return (String) get(Fields.BARCODE.toString());
    }

    public void setStoreLocation(String var) {
        set(Fields.STORE_LOCATION.toString(), var);
    }

    public String getStoreLocation() {
        return (String) get(Fields.STORE_LOCATION.toString());
    }

    public void setWeight(Integer var) {
        set(Fields.WEIGHT.toString(), var);
    }

    public Integer getWeight() {
        return (Integer) get(Fields.WEIGHT.toString());
    }

    public void setBulk(Integer var) {
        set(Fields.BULK.toString(), var);
    }

    public Integer getBulk() {
        return (Integer) get(Fields.BULK.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
