/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.product.model;

import com.jfeat.product.model.base.CarryModeBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

import java.util.List;

@TableBind(tableName = "t_carry_mode")
public class CarryMode extends CarryModeBase<CarryMode> {


    public static final int IS_DEFAULT = 1;
    public static final int NOT_DEFAULT = 0;

    public enum CarryWay {
        EXPRESS(0),
        EMS(1),
        NORMAL(2);

        private int value;
        CarryWay(int way) {
            this.value = way;
        }
        public int getValue() {
            return this.value;
        }
    }

    /**
     * Only use for query.
     */
    public static CarryMode dao = new CarryMode();

    public List<CarryMode> findByFareId(int fareId) {
        return find("select * from t_carry_mode where fare_id=? order by carry_way,is_default", fareId);
    }

    public CarryMode findByFareIdCarryWayDefault(int fareId,  CarryWay carryWay) {
        return findFirst("select * from t_carry_mode where fare_id=? and carry_way=? and is_default=1", fareId, carryWay.getValue());
    }

    public List<CarryMode> findByFareIdCarryWay(int fareId,  CarryWay carryWay) {
        return find("select * from t_carry_mode where fare_id=? and carry_way=?", fareId, carryWay.getValue());
    }
}
