/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.product.model;

import com.jfeat.product.model.base.InclPostageProvisoBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

import java.util.List;

@TableBind(tableName = "t_incl_postage_proviso")
public class InclPostageProviso extends InclPostageProvisoBase<InclPostageProviso> {

    public enum InclPostageType {
        PIECE_NO(0),
        WEIGHT_NO(1),
        BULK_NO(2),
        AMOUNT(3);

        private int value;
        InclPostageType(int way) {
            this.value = way;
        }
        public int getValue() {
            return this.value;
        }
    }


    /**
     * Only use for query.
     */
    public static InclPostageProviso dao = new InclPostageProviso();

    public List<InclPostageProviso> findByFareId(int fareId) {
        return find("select * from t_incl_postage_proviso where fare_id=?", fareId);
    }

    public List<InclPostageProviso> findByFareIdCarryWay(int fareId, CarryMode.CarryWay carryWay) {
        return find("select * from t_incl_postage_proviso where fare_id=? and carry_way=?", fareId, carryWay.getValue());
    }
}
