/*
 * Copyright (C) 2014-2015 by ehngjen @ www.jfeat.com
 *
 *  The program may be used and/or copied only with the written permission
 *  from JFeat.com, or in accordance with the terms and
 *  conditions stipulated in the agreement/contract under which the program
 *  has been supplied.
 *
 *  All rights reserved.
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.product.model;

import com.jfeat.product.model.base.ProductDescriptionBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

@TableBind(tableName = "t_product_description")
public class ProductDescription extends ProductDescriptionBase<ProductDescription> {

    /**
     * Only use for query.
     */
    public static ProductDescription dao = new ProductDescription();

    public ProductDescription findByProductId(int productId) {
        return findFirst("select * from t_product_description where product_id=?", productId);
    }
}
