/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.product.model;

import com.jfeat.product.model.base.ProductPropertyBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

@TableBind(tableName = "t_product_property")
public class ProductProperty extends ProductPropertyBase<ProductProperty> {

    /**
     * Only use for query.
     */
    public static ProductProperty dao = new ProductProperty();


    public List<ProductProperty> findByProductId(int productId) {
        return find("select pp.*, pcp.display_name, pcp.value_type from t_product_property as pp " +
                "inner join t_product_category_property as pcp on pp.property_id=pcp.id " +
                "where product_id=?", productId);
    }

    public void deleteByProductId(int productId) {
        Db.update("delete from t_product_property where product_id=?", productId);
    }
}
