/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.product.model;

import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import com.jfeat.product.model.base.ProductSpecificationBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.kit.StrKit;

import java.util.ArrayList;
import java.util.List;

@TableBind(tableName = "t_product_specification")
public class ProductSpecification extends ProductSpecificationBase<ProductSpecification> {

    /**
     * Only use for query.
     */
    public static ProductSpecification dao = new ProductSpecification();

    public List<ProductSpecification> findByProductId(int productId) {
        return find("select * from t_product_specification where product_id=? order by id asc", productId);
    }
}
