/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.product.model;

import com.jfeat.product.model.base.ProductPurchaseStrategyBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

@TableBind(tableName = "t_product_purchase_strategy")
public class ProductPurchaseStrategy extends ProductPurchaseStrategyBase<ProductPurchaseStrategy> {

    /**
     * Only use for query.
     */
    public static ProductPurchaseStrategy dao = new ProductPurchaseStrategy();

    public List<ProductPurchaseStrategyItem> getItems() {
        return ProductPurchaseStrategyItem.dao.findByStrategyId(getId());
    }

    public Long getProductCount() {
        return Db.queryLong("select count(*) from t_product_purchase_strategy_relation where strategy_id=?", getId());
    }

    public ProductPurchaseStrategy findByProductId(int productId) {
        return findFirst("select a.* from t_product_purchase_strategy a " +
                "join t_product_purchase_strategy_relation b on a.id=b.strategy_id " +
                "where b.product_id=?", productId);
    }

    public boolean updateItems(List<ProductPurchaseStrategyItem> items) {
        Db.update("delete from t_product_purchase_strategy_item where strategy_id=?", getId());
        for (ProductPurchaseStrategyItem item : items) {
            item.setStrategyId(getId());
            item.save();
        }
        return true;
    }


    public boolean updateProductStrategy(int productId, int strategyId) {
        String delete = "delete from t_product_purchase_strategy_relation where product_id=?";
        String insert = "insert into t_product_purchase_strategy_relation (product_id, strategy_id) values(?, ?)";
        Db.update(delete, productId);
        Db.update(insert, productId, strategyId);
        return true;
    }
}
