/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.product.model;

import com.jfeat.product.model.base.ProductCategoryPropertyBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

import java.util.List;

@TableBind(tableName = "t_product_category_property")
public class ProductCategoryProperty extends ProductCategoryPropertyBase<ProductCategoryProperty> {

    public enum ValueType {
        STRING,
        INTEGER,
        BOOLEAN,
        DATE
    }

    public enum InputType {
        INPUT_TEXT,
        INPUT_NUMBER,
        INPUT_DATE,
        TEXTAREA,
        CHECKBOX,
        RADIO,
        SELECT
    }

    /**
     * Only use for query.
     */
    public static ProductCategoryProperty dao = new ProductCategoryProperty();

    public List<ProductCategoryProperty> findByProductCategoryId(int categoryId) {
        return find("select * from t_product_category_property where category_id=?", categoryId);
    }
}
